#version: "3.9"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: 4m
    max-file: 10

x-depends_on:
  &default-depends_on
  cms-mariadb:
    condition: service_healthy

services:
  cms-nginx:
    image: nginx:1.26.1-bookworm
    # https://hub.docker.com/_/nginx
    container_name: cms-nginx
    hostname: "${HOSTNAME}_cms-nginx"
    restart: unless-stopped
    depends_on:
      << : *default-depends_on
      cms-wordpress:
        condition: service_healthy
    ports:
      - "127.0.0.1:50080:80"
    environment:
      TZ: ${TZ:-Europe/Paris}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9090/nginx_status || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging: *default-logging
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/status.conf:/etc/nginx/conf.d/status.conf:ro
      - wordpress-storage:/var/www/html

  cms-wordpress:
    build:
      context: ./wordpress/build
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Europe/Paris}
        WP_BACKUP_DATE: ${WP_BACKUP_DATE-"None"}
    image: cbna/cms-wordpress:wordpress-6.5.4-php8.3-fpm
    # https://hub.docker.com/_/wordpress
    container_name: cms-wordpress
    hostname: "${HOSTNAME}_cms-wordpress"
    restart: unless-stopped
    depends_on: *default-depends_on
    expose:
      - 9000
    environment:
      TZ: ${TZ:-Europe/Paris}
      WORDPRESS_DB_HOST: cms-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-floresent_}
      # WORDPRESS_DEBUG : use an empty string to disable
      WORDPRESS_DEBUG: ""
      # WORDPRESS_CONFIG_EXTRA: |
        # //define('FORCE_SSL_ADMIN', true);
        # define('WPMS_ON', true);
        # define('WPMS_SMTP_PASS', '${WPMS_SMTP_PASS}');
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - wordpress-storage:/var/www/html

  cms-wp-cli:
    # Usage:
    # - change site URL in database:
    #   `docker compose run --rm cms-wp-cli wp search-replace test.floresentinelle.fr floresentinelle.fr --all-tables`
    # - change site Scheme (http => https) :
    #   `docker compose run --rm cms-wp-cli wp option update home 'https://floresentinelle.fr'`
    #   `docker compose run --rm cms-wp-cli wp option update siteurl 'https://floresentinelle.fr'`
    image : wordpress:cli-2.10.0-php8.3
    # https://hub.docker.com/_/wordpress
    container_name: cms-wp-cli
    hostname: "${HOSTNAME}_cms-wp-cli"
    restart: "no"
    profiles: ["cli"]
    environment:
      TZ: ${TZ:-Europe/Paris}
      WORDPRESS_DB_HOST: cms-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-floresent_}
    depends_on:
      << : *default-depends_on
      cms-wordpress:
        condition: service_healthy
    volumes:
      - wordpress-storage:/var/www/html
      - ./backups:/backups

  cms-mariadb:
    image: mariadb:11.2.4-jammy
    # https://hub.docker.com/_/mariadb
    container_name: cms-mariadb
    hostname: "${HOSTNAME}_cms-mariadb"
    restart: unless-stopped
    expose:
      - 3306
    environment:
      TZ: ${TZ:-Europe/Paris}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      # See : https://github.com/docker-library/mariadb/issues/160
      MARIADB_INITDB_SKIP_TZINFO: "yes"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      interval: 1m30s
      timeout: 20s
      retries: 3
    logging: *default-logging
    volumes:
      - db-storage:/var/lib/mysql
      # Initialise Database with SQL files store in ./database/initdb.d/:
      - ./mariadb/initdb.d/:/docker-entrypoint-initdb.d/

  cms-adminer:
    image: adminer:4.8.1-standalone
    # https://hub.docker.com/_/adminer
    container_name: cms-adminer
    hostname: "${HOSTNAME}_cms-adminer"
    restart: unless-stopped
    ports:
      - "127.0.0.1:50081:8080"
    depends_on: *default-depends_on
    environment:
      TZ: ${TZ:-Europe/Paris}
      ADMINER_DESIGN: lucas-sandery
      ADMINER_DEFAULT_SERVER: cms-mariadb

  cms-backup-cron:
    build:
      context: ./cron/build
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Europe/Paris}
        MARIADB_REPO_SETUP_CHECKSUM: ${MARIADB_REPO_SETUP_CHECKSUM}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
    image: cbna/cms-backup-cron:debian-12.5-slim
    # https://hub.docker.com/_/debian
    container_name: cms-backup-cron
    hostname: "${HOSTNAME}_cms-backup-cron"
    restart: unless-stopped
    depends_on: *default-depends_on
    environment:
      TZ: ${TZ:-Europe/Paris}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_HOST: cms-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-floresent_}
    logging: *default-logging
    volumes:
        - wordpress-storage:/var/www/html
        - ./backups:/backups
        
volumes:
  db-storage:
  wordpress-storage:

networks:
  default:
    name: nginx-proxy
    external: true
