version: "3.9"

services:
  telegraf:
    image: telegraf:1.23.3
    container_name: telegraf
    # https://hub.docker.com/_/telegraf
    restart: unless-stopped
    ports:
      - "127.0.0.1:8125:8125/udp"
    hostname: ${HOSTNAME:-floresentinelle}
    # To authorize telgraf to access to /run/docker.sock set host docker gid
    # Find docker gid with: stat -c '%g' /var/run/docker.sock
    user: "telegraf:${DOCKER_GID:-997}"
    environment:
      HOSTNAME: ${HOSTNAME:-floresentinelle}
      HOST_MOUNT_PREFIX: /host
      HOST_ETC: /host/etc
      HOST_PROC: /host/proc
      HOST_RUN: /host/run
      HOST_SYS: /host/sys
      HOST_VAR: /host/var
      INFLUXDB2_INIT_ORG: ${INFLUXDB2_INIT_ORG}
      INFLUXDB2_INIT_BUCKET: ${INFLUXDB2_INIT_BUCKET}
      INFLUXDB2_TELEGRAF_TOKEN: ${INFLUXDB2_TELEGRAF_TOKEN}
    networks:
      - nginx-proxy
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/srvstatus/status.json:/opt/srvstatus/status.json

networks:
  nginx-proxy:
    external: true