source_directories:
  - /mnt/source/etc
  - /mnt/source/home
  - /mnt/source/opt
  - /mnt/source/root
  - /mnt/source/usr/local
one_file_system: true
files_cache: ctime,size,inode
repositories:
  - path: /mnt/borg-repository
    label: local
  - path: ssh://backups@10.0.1.10:60400/home/backups/floresentinelle-srv/
    label: sauvegarde-srv 
exclude_patterns:
  - /mnt/source/home/admin/docker/borgmatic/data/
  # Do not exclude this path  "- /mnt/source/root/.borgmatic/" with database backup.
  - /mnt/source/root/.config/borg
  - /mnt/source/root/.config/borgmatic
  - /mnt/source/*/.cache/
exclude_caches: true
exclude_if_present:
  - .nobackup

lock_wait: 5
temporary_directory: /tmp
compression: zstd,15
archive_name_format: 'floresentinelle-srv-{now}'

keep_hourly: 0
keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 3

checks:
  - repository
  - archives
check_last: 3

postgresql_databases:
  - name: geonature2db
    hostname: 172.18.5.1
    port: 5432
    # WARNING: use user with superadmin right and add "trust" for 172.18.5.1 in pg_hba.conf
    # With geonatadmin (not superuser) the dump can failed !
    username: postgres
    # WARNING : the "directory" format doesn't work ! Use the "custom" format instead.
    format: custom
    # WARNING : the below option does'nt work with "directory" format.
    #options: "--compress 9 --jobs=2"

before_everything:
  - "/usr/local/bin/telegram-send \"👷 Borgmatic ${HOSTNAME}: starting a backup job at `date` !\""
before_backup:
 - ping -q -c 1 10.0.1.10 > /dev/null || exit 75
after_everything:
 - "/usr/local/bin/telegram-send \"✅ Borgmatic ${HOSTNAME}: backup created at `date` ; size $(du --human-readable --null --summarize /mnt/borg-repository/ |cut --fields 1) !\""
on_error:
 - "/usr/local/bin/telegram-send \"🔥 Borgmatic ${HOSTNAME}: ERROR while creating a backup at `date` !\""
